### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by hehua2018** [ghaoo/rboot#9]
配置了.env 文件不生效

**Comment by ghaoo** [comment]
贴一下报错信息

**Comment by ghaoo** [comment]
我这里测试可以用的

**Comment by hehua2018** [comment]
我测试是变量，怎么都不生效嗯------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;ghaoo&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月13日(星期一) 下午5:36
收件人:&nbsp;&quot;ghaoo/rboot&quot;<rboot@noreply.github.com&gt;;
抄送:&nbsp;&quot;hehua2018&quot;<158702667@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ghaoo/rboot] .env (#9)

**Comment by ghaoo** [comment]
> 我测试是变量，怎么都不生效嗯------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;ghaoo&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年7月13日(星期一) 下午5:36 收件人:&nbsp;&quot;ghaoo/rboot&quot;<rboot@noreply.github.com&gt;; 抄送:&nbsp;&quot;hehua2018&quot;<158702667@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;; 主题:&nbsp;Re: [ghaoo/rboot] .env (#9)

是不是没放对地址？还是你在外部访问了？
